version: "3.8"
services:
  db:
    image: postgres
    container_name: product-configurator-db
    environment:
      - POSTGRES_DB"product_configurator
      - POSTGRES_USER=product_configurator
      - POSTGRES_PASSWORD=product_configurator
    ports:
      - "5432:5432"
  file-server:
    image: nginx
    container_name: product-configurator-file-server
    ports:
      - "8081:80"
    volumes:
      - $PWD/assets:/var/www/assets