version: "3.8"
services:
  db:
    image: postgres
    container_name: product-configurator-db
    environment:
      - POSTGRES_DB"product_configurator
      - POSTGRES_USER=product_configurator
      - POSTGRES_PASSWORD=product_configurator
    ports:
      - "5432:5432"
  gateway:
    image: caddy
    container_name: product-configurator-gateway
    ports:
      - "8081:8081"
    volumes:
      - $PWD/assets:/var/www/assets
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
